# Generated by Django 6.0.3 on 2026-03-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('sales', models.FloatField()),
                ('profit', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
            ],
        ),
    ]
